name: CI Checks (PR) and Deploy (Merge)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  ci_checks:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint Frontend Code
        working-directory: ./frontend
        run: npm run lint --if-present

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test --if-present -- --run

      - name: Build React App
        working-directory: ./frontend
        run: npm run build
        env:
          VITE_FITNESS_API_URL: ${{ secrets.API_GATEWAY_URL }}
          CI: false

      - name: Set up Node.js for Backend
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Lint Backend Code
        working-directory: ./backend
        run: npm run lint --if-present

      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test --if-present

      - name: Create Backend Deployment Package (ZIP)
        working-directory: ./backend
        run: zip -r ../backend-deployment.zip . -x ".git/*" "node_modules/aws-sdk/*"

      - name: Upload Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: ./frontend/dist

      - name: Upload Backend Deployment Package
        uses: actions/upload-artifact@v4
        with:
          name: backend-package
          path: ./backend-deployment.zip

  deploy:
    name: Deploy to AWS Learner Lab
    needs: ci_checks
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Configure AWS Credentials for Learner Lab
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build

      - name: Download Backend Deployment Package
        uses: actions/download-artifact@v4
        with:
          name: backend-package
          path: .

      - name: Deploy Frontend to S3
        run: |
          aws s3 sync ./frontend-build s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Deploy Backend to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://backend-deployment.zip

      - name: Deployment Summary
        run: |
          echo "Deployment to AWS completed successfully!"
          echo "Frontend deployed to S3 bucket: ${{ secrets.S3_BUCKET_NAME }}"
          echo "Backend deployed to Lambda function: ${{ secrets.LAMBDA_FUNCTION_NAME }}"
